server:
  port: 8080

spring:
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/test_11_21?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false # 缓存开关，默认开启：上线之后开启；研发期间关闭



# jwt自定义配置
jwt:
  expireTime: 30
  tokenSecret: qcbcyKey
